In [58]:
from data_processing.process_data import *
from utils import *

In [59]:
import torch
import os
from torch_geometric.data import Data
import pandas as pd
import numpy as np
from torchvision.transforms import ToTensor
from torch_geometric.loader import DataLoader
from tqdm.auto import trange, tqdm
from torch_geometric import seed_everything
import torchvision
import torch_geometric.nn as gnn

In [60]:
omics_file = "../data/raw/sm/kirp_sm251_csn.csv"
network_file = "../data/network/CancerSubnetwork.txt"
data2  = "../data/netprop/sm/kirp_sm251_csn_propagated.csv"

In [61]:
data = SingleOmicData(network_file, omics_file, 1)
num_nodes = len(data.node_order)

Loading the Network :  ../data/network/CancerSubnetwork.txt


100%|██████████| 2291/2291 [00:01<00:00, 1877.68it/s]


Loaded the Network 


In [62]:
model = gnn.GATv2Conv(1,1)

In [63]:
sum(data[0].x)

tensor([22.])

In [64]:
y = model(data[0].x, data[0].edge_index)
print(sum(y))
z = model(y, data[0].edge_index)
print(sum(z))
print(sum(model(z, data[0].edge_index)))

tensor([1822.6707], grad_fn=<AddBackward0>)
tensor([504.2202], grad_fn=<AddBackward0>)
tensor([1476.8541], grad_fn=<AddBackward0>)


In [67]:
data2 = pd.read_csv(data2, index_col=0)

In [68]:
sum(data2.iloc[0,:])

21.99999999999986

In [69]:
model2 = gnn.GravNetConv(1,1,4,3,2)

In [71]:
a = model2(data[0].x)

In [75]:
a.shape

torch.Size([2291, 1])